### ISSUE TITLE
pfe command

### ISSUE THREAD

**Issue by bmart847** [bmart847/BetterShell#3]

**Comment by bmart847** [comment]
Can't really be tested until shell is all set up and running.

**Comment by bmart847** [comment]
pfe _x_ _y_ Command now can be executed in the "Shell" branch. Currently getting segfault during the read_sector process though. But I will look into it.

**Comment by bmart847** [comment]
pfe command is now complete in the "Shell" branch

**Comment by bmart847** [comment]
#11

**Comment by joeListro** [comment]
Add access to shared memory

**Comment by bmart847** [comment]
Has access to shared mem. is currently a stub but will be implemented shortly

**Comment by bmart847** [comment]
Done with commit 9adc71dc31db2996d7157c93eca287172b333148 on branch: restructure

woohoo!
