### ISSUE TITLE
pbs command

### ISSUE THREAD

**Issue by bmart847** [bmart847/BetterShell#4]

**Comment by bmart847** [comment]
Basically done. Just needs to be merged. Have a look at my changes and add a bunch of comments when you get a chance Joe.

**Comment by bmart847** [comment]
#12 Pull request submitted and branch merged.

**Comment by joeListro** [comment]
Add access to shared memory

**Comment by bmart847** [comment]
Done with commit 19ad487888d0147a87a13e173ac9ee34bf7ada8d on branch restructure.
